Models/Proyecto.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlHrsConsultoria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proyecto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proyecto()
        {
            this.Proyecto_Consultor_Cliente = new HashSet<Proyecto_Consultor_Cliente>();
        }
    
        public int idProyecto { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaFinal { get; set; }
        public Nullable<decimal> montoPrecio { get; set; }
        public Nullable<decimal> costo { get; set; }
        public Nullable<bool> status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proyecto_Consultor_Cliente> Proyecto_Consultor_Cliente { get; set; }
    }
}

Models/ViewModel/ProyectoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ControlHrsConsultoria.Models.ViewModel
{
    public class ProyectoViewModel
    {
        public int IdProyecto { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFinal { get; set; }
        public Nullable<decimal> MontoPrecio { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}

Controllers/ProyectoController.cs
using ControlHrsConsultoria.Models;
using ControlHrsConsultoria.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControlHrsConsultoria.Controllers
{
    public class ProyectoController : Controller
    {
        // GET: Proyecto
        public ActionResult Index()
        {
            List<ProyectoViewModel> lst;

            using (ControlHrsConsultoriaEntities db = new ControlHrsConsultoriaEntities())
            {
                lst = (from d in db.Proyecto
                       select new ProyectoViewModel
                       {
                           IdProyecto = d.idProyecto,
                           Nombre = d.nombre,
                           Descripcion = d.descripcion,
                           FechaInicio = d.fechaInicio,
                           FechaFinal = d.fechaFinal,
                           MontoPrecio = d.montoPrecio,
                           Costo = d.costo,
                           Status = d.status
                       }).ToList();
            }
            return View(lst);
        }

        public ActionResult Nuevo()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Nuevo(FProyectoViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (ControlHrsConsultoriaEntities db = new ControlHrsConsultoriaEntities())
                    {
                        var oProyecto = new Proyecto();

                        oProyecto.nombre = model.Nombre;
                        oProyecto.descripcion = model.Descripcion;
                        oProyecto.fechaInicio = model.FechaInicio;
                        oProyecto.fechaFinal = model.FechaFinal;
                        oProyecto.montoPrecio = model.MontoPrecio;
                        oProyecto.costo = model.Costo;
                        oProyecto.status = model.Status;


                        db.Proyecto.Add(oProyecto);
                        db.SaveChanges();
                    }
                    return Redirect("~/Proyecto/");
                }
                return View(model);

            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }
        public ActionResult Editar(int Id)
        {
            FProyectoViewModel model = new FProyectoViewModel();
            using (ControlHrsConsultoriaEntities db = new ControlHrsConsultoriaEntities())
            {
                var oProyecto = db.Proyecto.Find(Id);

                model.IdProyecto = oProyecto.idProyecto;
                model.Nombre = oProyecto.nombre;
                model.Descripcion = oProyecto.descripcion;
                model.FechaInicio = oProyecto.fechaInicio;
                model.FechaFinal = oProyecto.fechaFinal;
                model.MontoPrecio = oProyecto.montoPrecio;
                model.Costo = oProyecto.costo;
                model.Status = (bool)oProyecto.status;
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Editar(FProyectoViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    
                    using (ControlHrsConsultoriaEntities db = new ControlHrsConsultoriaEntities())
                    {
                        var oProyecto = db.Proyecto.Find(model.IdProyecto);

                        oProyecto.nombre = model.Nombre;
                        oProyecto.descripcion = model.Descripcion;
                        oProyecto.fechaInicio = model.FechaInicio;
                        oProyecto.fechaFinal = model.FechaFinal;
                        oProyecto.montoPrecio = model.MontoPrecio;
                        oProyecto.costo = model.Costo;
                        oProyecto.status = model.Status;


                        db.Entry(oProyecto).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                    }
                    return Redirect("~/Proyecto/");
                }
                return View(model);

            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        [HttpGet]
        public ActionResult Eliminar(int Id)
        {
            using (ControlHrsConsultoriaEntities db = new ControlHrsConsultoriaEntities())
            {
                var oProyecto = db.Proyecto.Find(Id);
                db.Proyecto.Remove(oProyecto);
                db.SaveChanges();

            }
            return Redirect("~/Proyecto/");
        }
    }
}

Views/Proyecto/Editar.cshtml
@model ControlHrsConsultoria.Models.ViewModel.FProyectoViewModel

@{
    ViewBag.Title = "Editar proyecto";
}
<br />
<br />
<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Editar", "Proyecto", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-12">
            @Html.HiddenFor(d => d.IdProyecto)
            <div>
                @Html.LabelFor(d => d.Nombre)
                @Html.TextBoxFor(d => d.Nombre, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Nombre, null, new { @class = "red" })
            </div>
            <div>
                @Html.LabelFor(d => d.Descripcion)
                @Html.TextAreaFor(d => d.Descripcion, new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Descripcion, null, new { @class = "red" })
            </div>

            <div>
                @Html.LabelFor(d => d.MontoPrecio)
                @Html.TextBoxFor(d => d.MontoPrecio, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.MontoPrecio, null, new { @class = "red" })
            </div>

            <div>
                @Html.LabelFor(d => d.Costo)
                @Html.TextBoxFor(d => d.Costo, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Costo, null, new { @class = "red" })
            </div>

            <div class="row">
                <div class="col-md-6">
                    @Html.LabelFor(d => d.FechaInicio)<br />
                    @Html.EditorFor(d => d.FechaInicio, "", new { @class = "form-control" })
                    @Html.ValidationMessageFor(d => d.FechaInicio, null, new { @class = "red" })
                </div>

                <div class="col-md-6">
                    @Html.LabelFor(d => d.FechaFinal)<br />
                    @Html.EditorFor(d => d.FechaFinal, "", new { @class = "form-control" })
                    @Html.ValidationMessageFor(d => d.FechaFinal, null, new { @class = "red" })
                </div>
            </div>
            <br />
            <div>
                @Html.LabelFor(d => d.Status)
                @Html.CheckBoxFor(d => d.Status)
                @Html.ValidationMessageFor(d => d.Status, null, new { @class = "red" })
            </div>


            <div style="text-align:right;">
                <input value="Editar" class="btn btn-primary" type="submit" />
                <a href="~/Proyecto/" class="btn btn-danger">Cancelar</a>
            </div>

        </div>

    </div>

}

Views/Proyecto/Index.cshtml
@model List<ControlHrsConsultoria.Models.ViewModel.ProyectoViewModel>
@{
    ViewBag.Title = "Index";
}
<br />
<br />
<h2>Admin</h2>

<div class="row">
    <div class="col-md-2">
        <ul class="nav nav-pills nav-stacked">
            <li role="presentation" class="active"><a href="#">Proyectos</a></li>
            <li role="presentation"><a href="#">Consultores</a></li>
            <li role="presentation"><a href="#">Clientes</a></li>
        </ul>
    </div>
    <div class="col-md-10">
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <div class="row">
                    <div class="col-md-2"> Proyectos</div>
                    <div class="col-md-8"></div>
                    <div class="col-md-2"><a href="~/Proyecto/Nuevo" class="btm btn-primary" style="text-align: right; padding: 5px">Nuevo Proyecto</a></div>
                </div>
                
            </div>

            <!-- Table -->
            <table class="table">
                <tr>
                    <td>#</td>
                    <td>Nombre</td>
                    <td>Descripción</td>
                    <td>Precio $</td>
                    <td>Costo</td>
                    <td>Fecha Inicio</td>
                    <td>Fecha Final</td>
                    <td>Status</td>
                    <td>Acciones</td>
                </tr>
                @foreach (var oElemento in Model)
                {
            <tr>
                <td>@oElemento.IdProyecto</td>
                <td>@oElemento.Nombre</td>
                <td>@oElemento.Descripcion</td>
                <td>@oElemento.MontoPrecio</td>
                <td>@oElemento.Costo</td>
                <td>@oElemento.FechaInicio</td>
                <td>@oElemento.FechaFinal</td>
                <td>@oElemento.Status</td>
                <td>
                    <a class="btn btn-default" href="~/Proyecto/Editar/@oElemento.IdProyecto">Editar</a>
                    <a class="btn btn-danger" href="~/Proyecto/Eliminar/@oElemento.IdProyecto">Eliminar</a>
                </td>
            </tr>
                }
            </table>
        </div>
    </div>
</div>

Views/Proyecto/Nuevo.cshtml
@model ControlHrsConsultoria.Models.ViewModel.FProyectoViewModel
@{
    ViewBag.Title = "Nuevo Proyecto";
}
<br /><br />
<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Nuevo", "Proyecto", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-12">
            <div>
                @Html.LabelFor(d => d.Nombre)
                @Html.TextBoxFor(d => d.Nombre, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Nombre, null, new { @class = "red" })
            </div>
            <div>
                @Html.LabelFor(d => d.Descripcion)
                @Html.TextBoxFor(d => d.Descripcion, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Descripcion, null, new { @class = "red" })
            </div>

            <div>
                @Html.LabelFor(d => d.MontoPrecio)
                @Html.TextBoxFor(d => d.MontoPrecio, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.MontoPrecio, null, new { @class = "red" })
            </div>

            <div>
                @Html.LabelFor(d => d.Costo)
                @Html.TextBoxFor(d => d.Costo, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Costo, null, new { @class = "red" })
            </div>

            <div class="row">
                <div class="col-md-6">
                    @Html.LabelFor(d => d.FechaInicio)<br />
                    @Html.EditorFor(d => d.FechaInicio, "", new { @class = "form-control" })
                    @Html.ValidationMessageFor(d => d.FechaInicio, null, new { @class = "red" })
                </div>

                <div class="col-md-6">
                    @Html.LabelFor(d => d.FechaFinal)<br />
                    @Html.EditorFor(d => d.FechaFinal, "", new { @class = "form-control" })
                    @Html.ValidationMessageFor(d => d.FechaFinal, null, new { @class = "red" })
                </div>
            </div>
            <br />
            <div>
                @Html.LabelFor(d => d.Status)
                @Html.CheckBoxFor(d => d.Status)
                @Html.ValidationMessageFor(d => d.Status, null, new { @class = "red" })
            </div>

            <div style="text-align:right;">
                <input value="Guardar" class="btn btn-primary" type="submit" />
                <a href="~/Proyecto/" class="btn btn-danger">Cancelar</a>
            </div>

        </div>

    </div>

}

  