Models/Usuario.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlHrsConsultoria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Cliente = new HashSet<Cliente>();
            this.Consultor = new HashSet<Consultor>();
        }
    
        public int idUsuario { get; set; }
        public string nombre { get; set; }
        public string apellidos { get; set; }
        public string correo { get; set; }
        public string contraseña { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> idRol { get; set; }
        public Nullable<int> idCliente { get; set; }
        public string token_recovery { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cliente> Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consultor> Consultor { get; set; }
        public virtual Rol Rol { get; set; }
    }
}

Models/ViewModel/UsuarioViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ControlHrsConsultoria.Models.ViewModel
{
    public class UsuarioViewModel
    {
        [Required]
        [Display(Name = "ID usuario")]
        public int idUsuario { get; set; }
        [Required]
        [StringLength(50)]
        [MinLength(2)]
        [Display(Name = "Nombre")]
        public string nombre { get; set; }
        [Required]
        [StringLength(50)]
        [MinLength(2)]
        [Display(Name = "Apellidos")]
        public string apellidos { get; set; }
        [Required]
        [EmailAddress]
        [StringLength(50)]
        [MinLength(5)]
        [Display(Name = "Correo eléctronico")]
        public string correo { get; set; }
        [Required]
        [StringLength(50)]
        [MinLength(8)]
        [Display(Name = "Contraseña")]
        public string contraseña { get; set; }
        [Required]
        [Display(Name = "Fecha de registro")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<DateTime> fechaRegistro { get; set; }
        [Required]
        [Display(Name = "Estatus")]
        public Nullable<bool> status { get; set; }
        [Required]
        [Display(Name = "Rol de usuario")]
        public Nullable<int> idRol { get; set; }
        [Display(Name = "ID de cliente")]
        public Nullable<int> idCliente { get; set; }
    }
}

Controllers/UsuarioController.cs
using ControlHrsConsultoria.Models;
using ControlHrsConsultoria.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace ControlHrsConsultoria.Controllers
{
    public class UsuarioController : Controller
    {
        // GET: Usuario
        public ActionResult Index()
        {
            List<ListUsuarioViewModel> lst;
            using (ControlHrsConsultoriaEntities db = new ControlHrsConsultoriaEntities())
            {
                lst = (from t in db.Usuario
                           select new Models.ViewModel.ListUsuarioViewModel
                           {
                               idUsuario = t.idUsuario,
                               nombre = t.nombre,
                               apellidos = t.apellidos,
                               correo = t.correo,
                               contraseña = t.contraseña,
                               fechaRegistro = (DateTime)t.fechaRegistro,
                               status = (bool) t.status,
                               idRol = (int) t.idRol
                           }).ToList();
            }

            return View(lst);
        }
        public ActionResult Nuevo()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Nuevo(UsuarioViewModel model)
        {
            try 
            {
                if (ModelState.IsValid) 
                {
                    using (ControlHrsConsultoriaEntities db = new ControlHrsConsultoriaEntities())
                    {
                        var oUsuario = new Usuario();
                        oUsuario.idUsuario = model.idUsuario;
                        oUsuario.nombre = model.nombre;
                        oUsuario.apellidos = model.apellidos;
                        oUsuario.correo = model.correo;
                        oUsuario.contraseña = model.contraseña;
                        oUsuario.fechaRegistro = model.fechaRegistro;
                        oUsuario.status = model.status;
                        oUsuario.idRol = model.idRol;
                        oUsuario.idCliente = model.idCliente;

                        db.Usuario.Add(oUsuario);
                        db.SaveChanges();
                    }
                    return Redirect("~/Usuario/");

                }
                return View(model);
            } 
            catch (Exception e)
            {
                throw new Exception(e.Message);
            }

        }
        public ActionResult Editar(int IdUsuario)
        {
            UsuarioViewModel model = new UsuarioViewModel();
            using (ControlHrsConsultoriaEntities db = new ControlHrsConsultoriaEntities())
            {
                var oUsuario = db.Usuario.Find(IdUsuario);
                model.idUsuario = oUsuario.idUsuario;
                model.nombre = oUsuario.nombre;
                model.apellidos = oUsuario.apellidos;
                model.correo = oUsuario.correo;
                model.contraseña = oUsuario.contraseña;
                model.fechaRegistro = oUsuario.fechaRegistro;
                model.status = oUsuario.status;
                model.idRol = oUsuario.idRol;
                model.idCliente = oUsuario.idCliente;
            }
            return View(model);
        }
        [HttpPost]
        public ActionResult Editar(UsuarioViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (ControlHrsConsultoriaEntities db = new ControlHrsConsultoriaEntities())
                    {
                        var oUsuario = db.Usuario.Find(model.idUsuario);
                        oUsuario.idUsuario = model.idUsuario;
                        oUsuario.nombre = model.nombre;
                        oUsuario.apellidos = model.apellidos;
                        oUsuario.correo = model.correo;
                        oUsuario.contraseña = model.contraseña;
                        oUsuario.fechaRegistro = model.fechaRegistro;
                        oUsuario.status = model.status;
                        oUsuario.idRol = model.idRol;
                        oUsuario.idCliente = model.idCliente;

                        db.Entry(oUsuario).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                    }
                    return Redirect("~/Usuario/");

                }
                return View(model);
            }
            catch (Exception e)
            {
                throw new Exception(e.Message);
            }

        }

        [HttpGet]
        public ActionResult Eliminar(int IdUsuario)
        {
            using (ControlHrsConsultoriaEntities db = new ControlHrsConsultoriaEntities())
            {

                var oUsuario = db.Usuario.Find(IdUsuario);
                oUsuario.status = false;
                db.Entry(oUsuario).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
            return Redirect("~/Usuario/");
        }

        [HttpGet]
        public ActionResult EliminarFisico(int IdUsuario)
        {
            using (ControlHrsConsultoriaEntities db = new ControlHrsConsultoriaEntities())
            {

                var oUsuario = db.Usuario.Find(IdUsuario);
                db.Usuario.Remove(oUsuario);
                db.SaveChanges();
            }
            return Redirect("~/Usuario/");
        }

    }
}

Views/Usuario/Editar.cshtml
@model ControlHrsConsultoria.Models.ViewModel.UsuarioViewModel
@{
    ViewBag.Title = "Editar usuario";
}

<h2>@ViewBag.Title</h2>
@using (Html.BeginForm("Editar", "Usuario", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-12">
            @Html.HiddenFor(d => d.idUsuario)

            <div class="form-group">
                @Html.LabelFor(d => d.nombre)
                @Html.TextBoxFor(d => d.nombre, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.nombre, null, new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(d => d.apellidos)
                @Html.TextBoxFor(d => d.apellidos, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.apellidos, null, new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(d => d.correo)
                @Html.TextBoxFor(d => d.correo, "", new { @type = "email", @class = "form-control" })
                @Html.ValidationMessageFor(d => d.correo, null, new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(d => d.fechaRegistro)
                @Html.EditorFor(d => d.fechaRegistro, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.fechaRegistro, null, new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(d => d.status)
                <select name="status" id="status">
                    <option value="True">Habilitado</option>
                    <option value="False">Inhabilitado</option>
                </select>
                @Html.ValidationMessageFor(d => d.status, null, new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(d => d.idRol)
                @Html.TextBoxFor(d => d.idRol, "", new { @type = "number", @class = "form-control" })
                @Html.ValidationMessageFor(d => d.idRol, null, new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(d => d.idCliente)
                @Html.TextBoxFor(d => d.idCliente, "", new { @type = "number", @class = "form-control" })
                @Html.ValidationMessageFor(d => d.idCliente, null, new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(d => d.contraseña)
                @Html.TextBoxFor(d => d.contraseña, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.contraseña, null, new { @class = "text-danger" })
            </div>
            <div class="row" />
            <div style="text-align:right;">
                <input value="Guardar" class="btn btn-primary" type="submit" />
            </div>

        </div>
    </div>
}

Views/Usuario/Index.cshtml
@model List<ControlHrsConsultoria.Models.ViewModel.ListUsuarioViewModel>
@{
    ViewBag.Title = "Usuarios";
}

<h2>@ViewBag.Title</h2>

<div class="row" style="text-align:right;padding:5px;">
<a href="~/Usuario/Nuevo" class="btn btn-primary">Agregar usuario</a>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="table-responsive">
            <table class="table">
                <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Apellidos</th>
                    <th>Correo eléctronico</th>
                    <th>Fecha de registro</th>
                    <th>Estatus</th>
                    <th>Acciones</th>
                </tr>
                @foreach (var lstElemento in Model)
                {
                    <tr>
                        <td>@lstElemento.idUsuario</td>
                        <td>@lstElemento.nombre</td>
                        <td>@lstElemento.apellidos</td>
                        <td>@lstElemento.correo</td>
                        <td>@lstElemento.fechaRegistro</td>
                        <td>@lstElemento.status</td>
                        <td>
                            <a class="btn btn-default" href="~/Usuario/Editar?idUsuario=@lstElemento.idUsuario">Editar</a>
                            <a class="btn btn-danger" href="~/Usuario/Eliminar?idUsuario=@lstElemento.idUsuario">Eliminar</a>

                        </td>
                    </tr>
                }

            </table>
        </div>
    </div>
</div>

Views/Usuario/Nuevo.cshtml
@model ControlHrsConsultoria.Models.ViewModel.UsuarioViewModel
@{
    ViewBag.Title = "Registro usuario";
}

<h2>ViewBag.Title</h2>
@using (Html.BeginForm("Nuevo", "Usuario", FormMethod.Post)) {
<div class="row">
    <div class="col-md-12">

        <div class="form-group">
            @Html.LabelFor(d => d.nombre)
            @Html.TextBoxFor(d => d.nombre, "", new { @class = "form-control" })
            @Html.ValidationMessageFor(d => d.nombre, null, new { @class = "text-danger" })

        </div>

        <div class="form-group">
            @Html.LabelFor(d => d.apellidos)
            @Html.TextBoxFor(d => d.apellidos, "", new { @class = "form-control" })
        </div>

        <div class="form-group">
            @Html.LabelFor(d => d.correo)
            @Html.TextBoxFor(d => d.correo, "", new { @type = "email", @class = "form-control" })
        </div>

        <div class="form-group">
            @Html.LabelFor(d => d.fechaRegistro)
            @Html.EditorFor(d => d.fechaRegistro, "", new { @class = "form-control" })
        </div>

        <div class="form-group">
            @Html.LabelFor(d => d.status)
            <select name="status" id="status">
                <option value="True">Habilitado</option>
                <option value="False">Inhabilitado</option>
            </select>

        </div>

        <div class="form-group">
            @Html.LabelFor(d => d.idRol)
            @Html.TextBoxFor(d => d.idRol, "", new { @type = "number", @class = "form-control" })
        </div>

        <div class="form-group">
            @Html.LabelFor(d => d.idCliente)
            @Html.TextBoxFor(d => d.idCliente, "", new { @type = "number", @class = "form-control" })
        </div>

        <div class="form-group">
            @Html.LabelFor(d => d.contraseña)
            @Html.TextBoxFor(d => d.contraseña, "", new { @class = "form-control" })
        </div>
        <div class="row" />
        <div style="text-align:right;">
            <input value="Guardar" class="btn btn-primary" type="submit" />
        </div>

    </div>
</div>
}